### ISSUE TITLE
Merge readme.txt with README.md

### ISSUE THREAD

**Issue by dumbcoder7** [tradesouthwest/covidwebmd-assessment#1]
There seems to be no reason to have two different README files for the users feel confused.

It looks pretty simple to merge those two files into one so any GitHub user won't have to navigate to any other page to understand the issue.

You can assign the issue to me if you do not want to merge it yourself. Happy to help! But I definitely recommend combining them.

**Comment by tradesouthwest** [comment]
WordPress requires a readme.txt to parse all markup to the repository. Github does not require a README.md but it is nice to have so there is a minimal amount of info, if nothing else for init of a git commit.
